### ISSUE TITLE
Echo Tests are dependent on the order of child processes exectution

### ISSUE THREAD

**Issue by Graham42** [teppeis/grunt-parallelize#12]
This travis build log shows and example of the problem https://travis-ci.org/teppeis/grunt-parallelize/jobs/50600360#L239-L249

**Comment by Graham42** [comment]
New commits https://github.com/Graham42/grunt-parallelize/commit/489b718298c229ba7a5ce14a0a9700ce10301df0 and https://github.com/Graham42/grunt-parallelize/commit/57eae03972dd9ec47c2693ce759ea2bdff2eff18 fix the build in https://github.com/teppeis/grunt-parallelize/pull/11. If that PR is accepted, this can be closed.

**Comment by teppeis** [comment]
Fixed in https://github.com/teppeis/grunt-parallelize/pull/14. Thanks!
