### ISSUE TITLE
ENAMETOOLONG on too many files

### ISSUE THREAD

**Issue by asapach** [teppeis/grunt-parallelize#13]
I have several thousand files in my project, so trying to run a parallel task (e.g. eslint) via grunt-parallelize results in an error: `Fatal error: spawn ENAMETOOLONG`. It seems like the list of files is being passed to the grunt process via the command line arguments and the command line length reaches the OS limit (I'm on Windows). Maybe it would make sense to pass the list of files in temporary file or in similar fashion?

**Comment by asapach** [comment]
Oops, noticed #4. Need help merging it?

**Comment by teppeis** [comment]
fixed and released as v1.1.0!
