### ISSUE TITLE
Ability to specify target conditionally

### ISSUE THREAD

**Issue by scriby** [teppeis/grunt-parallelize#17]
Hi,

I would like to be able to configure grunt-parallelize to run tslint with a certain set of files in one case, and a different set of files in another case. As far as I can tell this configuration isn't possible (each parallelized task may only use one set of files).

Is my understanding correct, or is there a way to set this up now?

**Comment by teppeis** [comment]
You can configure 2 tasks and parallelize each task.

**Comment by scriby** [comment]
Oh, I didn't think it was possible with grunt to configure a task twice with a different name. I'll see if I can figure that out.

**Comment by teppeis** [comment]
That means, if you have`tslint:target1` and `tslint:target2`, you can parallelize them as `parallelize:tslint:target1` and `parallelize:tslint:target2`:

```javascript
  parallelize: {
    tshint: {
      target1: 2,
      target2: 2
    },
  },
```

**Comment by scriby** [comment]
Oh, can I just run one of them with "parallelize:tshint:target1"?

**Comment by teppeis** [comment]
Sorry, 2 ***targets***, not 2 tasks.

**Comment by scriby** [comment]
Hmm, that approach works with my "all" target, but not with my "changed" target. The only apparent difference between the two is the changed target specifies a filter which only keeps files which have changed.

The tslint:changed target does work ok by itself, but parallelize:tslint:changed indicates it didn't check any files.

Here is my task config:

```
tslint: {
      options: {
        configuration: grunt.file.readJSON('tslint.json'),
        formatter: 'tslint',
        formattersDirectory: './'
      },
      
      all: {
        src: [ 'app/**/*.ts', 'test/**/*.ts' ]
      },
      
      //This target only lints files which have changed in this branch
      changed: {
        src: [ 'app/**/*.ts', 'test/**/*.ts' ],
        
        filter: function(src) {
          return grunt.config.get('git.changed').indexOf(src) >= 0 ||  //File was modified, but not yet committed
                 grunt.config.get('refChangedFiles').indexOf(src) >= 0; //File was committed previously in this branch
        }
      }
    }
```

And my verbose output:

```
    Running tasks: parallelize:tslint:changed
    
    Running "parallelize:tslint:changed" (parallelize) task
    Verifying property parallelize.tslint exists in config...OK
    File: [no files]
    
    Running "tslint:changed" (tslint) task
    Verifying property tslint.changed exists in config...OK
    Files: [no src]
    Options: formatter="tslint", outputFile=null, configuration={"rules":{"class-name":true,"curly":true,"indent":[true,2],"interface-name":true,"jsdoc-format":false,"label-position":true,"label-undefined":true,"max-line-length":[true,140],"no-arg":true,"no-bitwise":true,"no-consecutive-blank-lines":true,"no-construct":true,"no-debugger":true,"no-duplicate-key":true,"no-duplicate-variable":true,"no-empty":true,"no-eval":true,"no-string-literal":true,"no-switch-case-fall-through":true,"no-unused-expression":true,"no-unreachable":true,"no-use-before-declare":true,"no-var-requires":true,"one-line":[true,"check-open-brace","check-catch","check-else","check-whitespace"],"quotemark":[true,"single"],"radix":true,"semicolon":true,"triple-equals":[true,"allow-null-check"],"typedef-whitespace":[true,["callSignature","noSpace"],["catchClause","noSpace"],["indexSignature","noSpace"]],"use-strict":[true,"check-module"],"whitespace":[true,"check-branch","check-decl","check-operator","check-separator","check-type"]}}, formattersDirectory="./"
    >> 0 files lint free.
    
    Done, without errors.
```

**Comment by teppeis** [comment]
What's `grunt.config.get('git.changed')`?
Can I see the whole gruntfile?

**Comment by scriby** [comment]
git.changed is a property set by the git_changedfiles plugin. I'm pretty confident that part works, because if I replace "parallelize:tslint:changed" with just "tslint:changed", it works.

Here is the other relevant portion:

```
  grunt.registerTask('pre-commit', [
    'ddescribe-iit',
    'git_changedfiles',
    'refChangedFiles',
    'parallelize:tslint:changed',
    ...
  ]);
```

The whole gruntfile is over 1,000 lines... not sure you want to see it all :0

**Comment by scriby** [comment]
The number of changed files will be pretty small, so this is not really a big problem for me. If it's going to be a pain to figure out I'm ok with just not running that part in parallel.

**Comment by teppeis** [comment]
> Once the task has run, you'll then be able to access a list of files changed in your Git working tree like this:
> ```
> grunt.config.get('git.changed')
> ```
> https://github.com/causata/grunt-git-changedfiles

But each parallelized task is executed in a spawned process alone.
"git_changedfiles" task is not executed and `git.changed` is not available there.
Sorry.

**Comment by scriby** [comment]
Ok, thanks for the explanation!
