### ISSUE TITLE
Takes longer with number of processes in global `options` than in each task options

### ISSUE THREAD

**Issue by benbuckman** [teppeis/grunt-parallelize#3]
First, thanks for creating this, this has the potential to save a lot of time.

I'm trying to use this to speed up our [grunt-coffeelint](https://github.com/vojtajina/grunt-coffeelint) tasks and I'm seeing something strange: When I set the number of processes globally, like

```javascript
config.parallelize = {
  options: {
    processes: require('os').cpus().length
  }
};
```

then the tasks run in 8 seconds (using `time` to measure).

When I set it directly on the coffeelint task, however, like

```javascript
config.parallelize.coffeelint = {
  all: require('os').cpus().length
};
```

Then it runs in 7 seconds.
In both cases, adding logging to `getSplittedFilesSrc_` indicates that it's using the same 8 processes. But something else must be different in the way it's processing them, because it's consistently 1 second longer to run with the global option.

Any idea why?

Thanks!

**Comment by teppeis** [comment]
@benbuckman Sorry, I can't reproduce it.
Please reopen and report if you have some additional information. Thanks.
