### ISSUE TITLE
Unable to run with either traceur or react

### ISSUE THREAD

**Issue by bennidhamma** [teppeis/grunt-parallelize#7]
With react I get this error:

    Running "clean:dist" (clean) task

    Running "parallelize:react:app" (parallelize) task
    
    Running "react:app" (react) task
    Warning: Cannot read property 'cyan' of undefined Use --force to continue.
    
    Aborted due to warnings.
        
    Running "react:app" (react) task
    Warning: Cannot read property 'cyan' of undefined Use --force to continue.
    
    Aborted due to warnings.
        
    Running "react:app" (react) task
    Warning: Cannot read property 'cyan' of undefined Use --force to continue.
    
    Aborted due to warnings.
        
    Running "react:app" (react) task
    Warning: Cannot read property 'cyan' of undefined Use --force to continue.
    
    Aborted due to warnings.
    
    Warning: Task "parallelize:react:app" failed. Use --force to continue.

    Aborted due to warnings.

And with traceur:

   Running "parallelize:traceur:app" (parallelize) task
    
    Running "traceur:app" (traceur) task
    Fatal error: Unable to write "undefined" file (Error code: undefined).
        
    Running "traceur:app" (traceur) task
    Fatal error: Unable to write "undefined" file (Error code: undefined).
        
    Running "traceur:app" (traceur) task
    Fatal error: Unable to write "undefined" file (Error code: undefined).
        
    Running "traceur:app" (traceur) task
    Fatal error: Unable to write "undefined" file (Error code: undefined).
    
    Warning: Task "parallelize:traceur:app" failed. Use --force to continue.

Aborted due to warnings.

Any ideas?

**Comment by teppeis** [comment]
@bennidhamma fixed and released! sorry to be late.
